name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Worker
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20.3.0"

      - name: Yarn Install
        run: yarn install

      - name: Wrangler Install
        run: npm install -g wrangler

      - name: Get UbiquiBot Token
        uses: tibdex/github-app-token@v1.7.0
        id: get_installation_token
        with:
          app_id: ${{ secrets.UBIQUITY_BOUNTY_BOT_APP_ID }}
          private_key: ${{ secrets.UBIQUITY_BOUNTY_BOT_PRIVATE_KEY }}

      - name: Publish to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          WEBHOOK: "/endpoint"
          SECRET: ${{ secrets.BOT_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_PAT: ${{ secrets.PAT }}
          DEFAULT_PRIORITY: "Priority: 0 (Normal)"
          INSTALLATION_TOKEN: ${{ steps.get_installation_token.outputs.token }}
        run: |
          # Populate Cloudflare Worker secrets
          echo "$TOKEN" | wrangler secret put TOKEN
          echo "$WEBHOOK" | wrangler secret put WEBHOOK
          echo "$SECRET" | wrangler secret put SECRET
          echo "$OPENAI_API_KEY" | wrangler secret put OPENAI_API_KEY
          echo "$GITHUB_PAT" | wrangler secret put GITHUB_PAT
          echo "$DEFAULT_PRIORITY" | wrangler secret put DEFAULT_PRIORITY
          echo "$INSTALLATION_TOKEN" | wrangler secret put INSTALLATION_TOKEN

          yarn deploy
